iservices:
  insync:
    image: ghcr.io/hcastilho/insync-headless:latest
    container_name: insync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - .config:/root/.config/Insync:z
      - ${VAULT_PATH}:/data:rw,Z
    restart: unless-stopped