services:
  insync:
    image: ghcr.io/hcastilho/insync-headless:latest
    container_name: insync
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - ./config:/home/ubuntu/.config/Insync-headless:Z
      - ${VAULT_PATH}:/data:rw,z
    restart: unless-stopped
